import { MemberListItem } from "./member.dto";

export const MOCK_MEMBERS: MemberListItem[] = [
  {
    memberId: "m1",
    identifier: "cashier_001",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "manager",
    company: {
      code: "COMP01",
      email: "manager@techcorp.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Tech Corp",
      phone: "555-0101",
      uuid: "c1",
    },
  },
  {
    memberId: "m2",
    identifier: "cashier_002",
    approvalStatus: "PENDING",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP02",
      email: "info@greenearth.org",
      logoImageUrl: "https://placehold.co/100",
      name: "Green Earth",
      phone: "555-0102",
      uuid: "c2",
    },
  },
  {
    memberId: "m3",
    identifier: "cashier_003",
    approvalStatus: "REJECTED",
    isActive: false,
    permission: "cashier",
    company: {
      code: "COMP03",
      email: "contact@fastfood.io",
      logoImageUrl: "https://placehold.co/100",
      name: "Fast Food IO",
      phone: "555-0103",
      uuid: "c3",
    },
  },
  {
    memberId: "m4",
    identifier: "cashier_004",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "manager",
    company: {
      code: "COMP04",
      email: "support@cloudnet.net",
      logoImageUrl: "https://placehold.co/100",
      name: "Cloud Net",
      phone: "555-0104",
      uuid: "c4",
    },
  },
  {
    memberId: "m5",
    identifier: "cashier_005",
    approvalStatus: "PENDING",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP05",
      email: "hello@brightside.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Bright Side",
      phone: "555-0105",
      uuid: "c5",
    },
  },
  {
    memberId: "m6",
    identifier: "cashier_006",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP06",
      email: "ops@logistics.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Global Logistics",
      phone: "555-0106",
      uuid: "c6",
    },
  },
  {
    memberId: "m7",
    identifier: "cashier_007",
    approvalStatus: "REJECTED",
    isActive: false,
    permission: "cashier",
    company: {
      code: "COMP07",
      email: "sales@automotive.io",
      logoImageUrl: "https://placehold.co/100",
      name: "Auto Drive",
      phone: "555-0107",
      uuid: "c7",
    },
  },
  {
    memberId: "m8",
    identifier: "cashier_008",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP08",
      email: "billing@retailhub.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Retail Hub",
      phone: "555-0108",
      uuid: "c8",
    },
  },
  {
    memberId: "m9",
    identifier: "cashier_009",
    approvalStatus: "PENDING",
    isActive: true,
    permission: "manager",
    company: {
      code: "COMP09",
      email: "dev@softwareco.net",
      logoImageUrl: "https://placehold.co/100",
      name: "Software Co",
      phone: "555-0109",
      uuid: "c9",
    },
  },
  {
    memberId: "m10",
    identifier: "cashier_010",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "manager",
    company: {
      code: "COMP10",
      email: "ceo@visionary.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Visionary Inc",
      phone: "555-0110",
      uuid: "c10",
    },
  },
  {
    memberId: "m11",
    identifier: "cashier_011",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP11",
      email: "staff@hospitality.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Grand Hotel",
      phone: "555-0111",
      uuid: "c11",
    },
  },
  {
    memberId: "m12",
    identifier: "cashier_012",
    approvalStatus: "PENDING",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP12",
      email: "info@cleanwater.org",
      logoImageUrl: "https://placehold.co/100",
      name: "Pure Water",
      phone: "555-0112",
      uuid: "c12",
    },
  },
  {
    memberId: "m13",
    identifier: "cashier_013",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP13",
      email: "desk@bakery.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Daily Bread",
      phone: "555-0113",
      uuid: "c13",
    },
  },
  {
    memberId: "m14",
    identifier: "cashier_014",
    approvalStatus: "REJECTED",
    isActive: false,
    permission: "manager",
    company: {
      code: "COMP14",
      email: "hr@fintech.io",
      logoImageUrl: "https://placehold.co/100",
      name: "Secure Pay",
      phone: "555-0114",
      uuid: "c14",
    },
  },
  {
    memberId: "m15",
    identifier: "cashier_015",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP15",
      email: "team@marketing.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Creative Pulse",
      phone: "555-0115",
      uuid: "c15",
    },
  },
  {
    memberId: "m16",
    identifier: "cashier_016",
    approvalStatus: "PENDING",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP16",
      email: "legal@firm.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Justice Law",
      phone: "555-0116",
      uuid: "c16",
    },
  },
  {
    memberId: "m17",
    identifier: "cashier_017",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "manager",
    company: {
      code: "COMP17",
      email: "it@government.gov",
      logoImageUrl: "https://placehold.co/100",
      name: "Public Sector",
      phone: "555-0117",
      uuid: "c17",
    },
  },
  {
    memberId: "m18",
    identifier: "cashier_018",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP18",
      email: "order@delivery.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Swift Ship",
      phone: "555-0118",
      uuid: "c18",
    },
  },
  {
    memberId: "m19",
    identifier: "cashier_019",
    approvalStatus: "PENDING",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP19",
      email: "manager@cinema.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Star Movies",
      phone: "555-0119",
      uuid: "c19",
    },
  },
  {
    memberId: "m20",
    identifier: "cashier_020",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "manager",
    company: {
      code: "COMP20",
      email: "support@fitness.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Iron Gym",
      phone: "555-0120",
      uuid: "c20",
    },
  },
  {
    memberId: "m21",
    identifier: "cashier_021",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP21",
      email: "hello@flowers.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Rose Garden",
      phone: "555-0121",
      uuid: "c21",
    },
  },
  {
    memberId: "m22",
    identifier: "cashier_022",
    approvalStatus: "REJECTED",
    isActive: false,
    permission: "cashier",
    company: {
      code: "COMP22",
      email: "manager@construction.net",
      logoImageUrl: "https://placehold.co/100",
      name: "Solid Build",
      phone: "555-0122",
      uuid: "c22",
    },
  },
  {
    memberId: "m23",
    identifier: "cashier_023",
    approvalStatus: "PENDING",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP23",
      email: "contact@education.edu",
      logoImageUrl: "https://placehold.co/100",
      name: "Alpha Academy",
      phone: "555-0123",
      uuid: "c23",
    },
  },
  {
    memberId: "m24",
    identifier: "cashier_024",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP24",
      email: "shop@boutique.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Urban Style",
      phone: "555-0124",
      uuid: "c24",
    },
  },
  {
    memberId: "m25",
    identifier: "cashier_025",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "manager",
    company: {
      code: "COMP25",
      email: "info@travel.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Sky High",
      phone: "555-0125",
      uuid: "c25",
    },
  },
  {
    memberId: "m26",
    identifier: "cashier_026",
    approvalStatus: "PENDING",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP26",
      email: "web@digital.io",
      logoImageUrl: "https://placehold.co/100",
      name: "Pixel Perfect",
      phone: "555-0126",
      uuid: "c26",
    },
  },
  {
    memberId: "m27",
    identifier: "cashier_027",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP27",
      email: "support@pharma.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Medi Care",
      phone: "555-0127",
      uuid: "c27",
    },
  },
  {
    memberId: "m28",
    identifier: "cashier_028",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "manager",
    company: {
      code: "COMP28",
      email: "lead@security.net",
      logoImageUrl: "https://placehold.co/100",
      name: "Safe Guard",
      phone: "555-0128",
      uuid: "c28",
    },
  },
  {
    memberId: "m29",
    identifier: "cashier_029",
    approvalStatus: "REJECTED",
    isActive: false,
    permission: "cashier",
    company: {
      code: "COMP29",
      email: "frontdesk@hotel.io",
      logoImageUrl: "https://placehold.co/100",
      name: "Blue Resort",
      phone: "555-0129",
      uuid: "c29",
    },
  },
  {
    memberId: "m30",
    identifier: "cashier_030",
    approvalStatus: "PENDING",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP30",
      email: "hello@coffee.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Bean Street",
      phone: "555-0130",
      uuid: "c30",
    },
  },
  {
    memberId: "m31",
    identifier: "cashier_031",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "manager",
    company: {
      code: "COMP31",
      email: "ops@factory.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Power Plant",
      phone: "555-0131",
      uuid: "c31",
    },
  },
  {
    memberId: "m32",
    identifier: "cashier_032",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP32",
      email: "help@gaming.io",
      logoImageUrl: "https://placehold.co/100",
      name: "Level Up",
      phone: "555-0132",
      uuid: "c32",
    },
  },
  {
    memberId: "m33",
    identifier: "cashier_033",
    approvalStatus: "PENDING",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP33",
      email: "staff@events.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Party Plan",
      phone: "555-0133",
      uuid: "c33",
    },
  },
  {
    memberId: "m34",
    identifier: "cashier_034",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP34",
      email: "sales@furniture.net",
      logoImageUrl: "https://placehold.co/100",
      name: "Home Nest",
      phone: "555-0134",
      uuid: "c34",
    },
  },
  {
    memberId: "m35",
    identifier: "cashier_035",
    approvalStatus: "REJECTED",
    isActive: false,
    permission: "cashier",
    company: {
      code: "COMP35",
      email: "billing@insurance.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Shield Co",
      phone: "555-0135",
      uuid: "c35",
    },
  },
  {
    memberId: "m36",
    identifier: "cashier_036",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "manager",
    company: {
      code: "COMP36",
      email: "dev@robotics.io",
      logoImageUrl: "https://placehold.co/100",
      name: "Future Bot",
      phone: "555-0136",
      uuid: "c36",
    },
  },
  {
    memberId: "m37",
    identifier: "cashier_037",
    approvalStatus: "PENDING",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP37",
      email: "contact@realestate.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Prime Land",
      phone: "555-0137",
      uuid: "c37",
    },
  },
  {
    memberId: "m38",
    identifier: "cashier_038",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP38",
      email: "support@music.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Sound Wave",
      phone: "555-0138",
      uuid: "c38",
    },
  },
  {
    memberId: "m39",
    identifier: "cashier_039",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP39",
      email: "orders@pizza.io",
      logoImageUrl: "https://placehold.co/100",
      name: "Hot Slice",
      phone: "555-0139",
      uuid: "c39",
    },
  },
  {
    memberId: "m40",
    identifier: "cashier_040",
    approvalStatus: "PENDING",
    isActive: true,
    permission: "manager",
    company: {
      code: "COMP40",
      email: "manager@banking.net",
      logoImageUrl: "https://placehold.co/100",
      name: "Wealth Bank",
      phone: "555-0140",
      uuid: "c40",
    },
  },
  {
    memberId: "m41",
    identifier: "cashier_041",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP41",
      email: "team@design.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Art Studio",
      phone: "555-0141",
      uuid: "c41",
    },
  },
  {
    memberId: "m42",
    identifier: "cashier_042",
    approvalStatus: "REJECTED",
    isActive: false,
    permission: "cashier",
    company: {
      code: "COMP42",
      email: "info@nature.org",
      logoImageUrl: "https://placehold.co/100",
      name: "Wild Life",
      phone: "555-0142",
      uuid: "c42",
    },
  },
  {
    memberId: "m43",
    identifier: "cashier_043",
    approvalStatus: "PENDING",
    isActive: true,
    permission: "manager",
    company: {
      code: "COMP43",
      email: "ops@energy.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Sun Power",
      phone: "555-0143",
      uuid: "c43",
    },
  },
  {
    memberId: "m44",
    identifier: "cashier_044",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP44",
      email: "help@electronics.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Circuit City",
      phone: "555-0144",
      uuid: "c44",
    },
  },
  {
    memberId: "m45",
    identifier: "cashier_045",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP45",
      email: "sales@fashion.io",
      logoImageUrl: "https://placehold.co/100",
      name: "Vogue Hub",
      phone: "555-0145",
      uuid: "c45",
    },
  },
  {
    memberId: "m46",
    identifier: "cashier_046",
    approvalStatus: "PENDING",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP46",
      email: "contact@consulting.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Expert Path",
      phone: "555-0146",
      uuid: "c46",
    },
  },
  {
    memberId: "m47",
    identifier: "cashier_047",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP47",
      email: "staff@shipping.net",
      logoImageUrl: "https://placehold.co/100",
      name: "Ocean Cargo",
      phone: "555-0147",
      uuid: "c47",
    },
  },
  {
    memberId: "m48",
    identifier: "cashier_048",
    approvalStatus: "REJECTED",
    isActive: false,
    permission: "manager",
    company: {
      code: "COMP48",
      email: "hr@telecom.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Fast Talk",
      phone: "555-0148",
      uuid: "c48",
    },
  },
  {
    memberId: "m49",
    identifier: "cashier_049",
    approvalStatus: "PENDING",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP49",
      email: "web@media.io",
      logoImageUrl: "https://placehold.co/100",
      name: "Buzz Feed",
      phone: "555-0149",
      uuid: "c49",
    },
  },
  {
    memberId: "m50",
    identifier: "cashier_050",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "manager",
    company: {
      code: "COMP50",
      email: "ceo@enterprise.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Big Scale",
      phone: "555-0150",
      uuid: "c50",
    },
  },
];
