import { MemberListItem } from "./member.dto";

export const MOCK_MEMBERS: MemberListItem[] = [
  {
    memberId: "m1",
    identifier: "cashier_001",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "manager",
    company: {
      code: "COMP01",
      email: "manager@techcorp.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Tech Corp",
      phone: "555-0101",
      uuid: "c1",
    },
  },
  {
    memberId: "m2",
    identifier: "cashier_002",
    approvalStatus: "PENDING",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP02",
      email: "info@greenearth.org",
      logoImageUrl: "https://placehold.co/100",
      name: "Green Earth",
      phone: "555-0102",
      uuid: "c2",
    },
  },
  {
    memberId: "m3",
    identifier: "cashier_003",
    approvalStatus: "REJECTED",
    isActive: false,
    permission: "cashier",
    company: {
      code: "COMP03",
      email: "contact@fastfood.io",
      logoImageUrl: "https://placehold.co/100",
      name: "Fast Food IO",
      phone: "555-0103",
      uuid: "c3",
    },
  },
  {
    memberId: "m4",
    identifier: "cashier_004",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "manager",
    company: {
      code: "COMP04",
      email: "support@cloudnet.net",
      logoImageUrl: "https://placehold.co/100",
      name: "Cloud Net",
      phone: "555-0104",
      uuid: "c4",
    },
  },
  {
    memberId: "m5",
    identifier: "cashier_005",
    approvalStatus: "PENDING",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP05",
      email: "hello@brightside.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Bright Side",
      phone: "555-0105",
      uuid: "c5",
    },
  },
  {
    memberId: "m6",
    identifier: "cashier_006",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP06",
      email: "ops@logistics.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Global Logistics",
      phone: "555-0106",
      uuid: "c6",
    },
  },
  {
    memberId: "m7",
    identifier: "cashier_007",
    approvalStatus: "REJECTED",
    isActive: false,
    permission: "cashier",
    company: {
      code: "COMP07",
      email: "sales@automotive.io",
      logoImageUrl: "https://placehold.co/100",
      name: "Auto Drive",
      phone: "555-0107",
      uuid: "c7",
    },
  },
  {
    memberId: "m8",
    identifier: "cashier_008",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP08",
      email: "billing@retailhub.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Retail Hub",
      phone: "555-0108",
      uuid: "c8",
    },
  },
  {
    memberId: "m9",
    identifier: "cashier_009",
    approvalStatus: "PENDING",
    isActive: true,
    permission: "manager",
    company: {
      code: "COMP09",
      email: "dev@softwareco.net",
      logoImageUrl: "https://placehold.co/100",
      name: "Software Co",
      phone: "555-0109",
      uuid: "c9",
    },
  },
  {
    memberId: "m10",
    identifier: "cashier_010",
    approvalStatus: "APPROVED",
    isActive: true,
    permission: "manager",
    company: {
      code: "COMP10",
      email: "ceo@visionary.com",
      logoImageUrl: "https://placehold.co/100",
      name: "Visionary Inc",
      phone: "555-0110",
      uuid: "c10",
    },
  },
  {
    memberId: "m11",
    identifier: "cashier_011",
    approvalStatus: "PENDING",
    isActive: true,
    permission: "cashier",
    company: {
      code: "COMP11",
      email: "support@digital.co",
      logoImageUrl: "https://placehold.co/100",
      name: "Digital Solutions",
      phone: "555-0111",
      uuid: "c11",
    },
  },
  {
    memberId: "m12",
    identifier: "cashier_012",
    approvalStatus: "APPROVED",
    isActive: false,
    permission: "cashier",
    company: {
      code: "COMP12",
      email: "info@fusion.io",
      logoImageUrl: "https://placehold.co/100",
      name: "Fusion Labs",
      phone: "555-0112",
      uuid: "c12",
    },
  },
];


